name: Update README

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - run: go run main.go
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update generated README
