name: Update universe

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * sun"

jobs:
  update:
    runs-on: ubuntu-latest
    if: "!endsWith(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - run: go run .
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update universe
